### ISSUE TITLE
[TODO] Kernel

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/ClassicOS#51]
Our bootloader is now complete and working.

Here are the TODO items for our Kernel in C11.  

- [ ] Set up the kernel Global Descriptor Table (GDT)
   - [ ] Define segments for code and data
   - [ ] Implement GDT loading code
- [ ] Implement a Interrupt Descriptor Table (IDT)
   - [ ] Set up interrupt handlers for CPU exceptions
   - [ ] Create a basic Interrupt Service Routine (ISR) framework
      - [ ]  Write ISRs for common interrupts like keyboard, timer, and system calls
- [ ] Enable paging
   - [ ] Set up page directory and page tables
   - [ ] Enable paging in the CPU
   - [ ] Use segment descriptors
